import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { isAbsolute, resolve } from "node:path";
import { z } from "zod";

export const ThemeColorsSchema = z.object({
  ink: z.string().regex(/^[0-9a-f]{6}$/i),
  muted: z.string().regex(/^[0-9a-f]{6}$/i),
  line: z.string().regex(/^[0-9a-f]{6}$/i),
  accent: z.string().regex(/^[0-9a-f]{6}$/i),
  canvas: z.string().regex(/^[0-9a-f]{6}$/i),
  surface: z.string().regex(/^[0-9a-f]{6}$/i)
});
export const ThemeLogoSchema = z.object({ path: z.string().min(1), x: z.number().min(0).max(13.33).default(11.5), y: z.number().min(0).max(7.5).default(0.2), w: z.number().positive().max(3).default(1), h: z.number().positive().max(2).default(0.35) });
export const DeckThemeSchema = z.object({
  fontFace: z.string().min(1),
  headingFontFace: z.string().min(1),
  colors: ThemeColorsSchema,
  footer: z.string().optional(),
  logoPath: z.string().min(1).optional(),
  logo: ThemeLogoSchema.optional(),
  margin: z.number().min(0).max(2)
});
export type DeckTheme = z.infer<typeof DeckThemeSchema>;
export type ResolvedTheme = DeckTheme;
export type DeckThemeInput = {
  fontFace?: string;
  headingFontFace?: string;
  colors?: Partial<DeckTheme["colors"]>;
  footer?: string;
  logoPath?: string;
  logo?: Partial<NonNullable<DeckTheme["logo"]>>;
  margin?: number;
};

export const defaultTheme: DeckTheme = {
  fontFace: "Aptos",
  headingFontFace: "Aptos Display",
  colors: { ink: "111827", muted: "6B7280", line: "E5E7EB", accent: "2563EB", canvas: "FFFFFF", surface: "F9FAFB" },
  footer: "Generated by Local Deck AI",
  margin: 0.85
};

const themeInputSchema = DeckThemeSchema.partial().extend({ colors: ThemeColorsSchema.partial().optional(), logo: ThemeLogoSchema.partial().optional() });

export function resolveTheme(theme?: DeckThemeInput): DeckTheme {
  const merged = {
    ...defaultTheme,
    ...theme,
    colors: { ...defaultTheme.colors, ...(theme?.colors ?? {}) },
    logo: theme?.logo ? { ...(defaultTheme.logo ?? {}), ...theme.logo } : theme?.logoPath ? undefined : defaultTheme.logo
  };
  const parsed = DeckThemeSchema.safeParse(merged);
  if (!parsed.success) throw new Error(`Invalid theme:\n${parsed.error.message}`);
  const errors = validateTheme(parsed.data);
  if (errors.length > 0) throw new Error(`Invalid theme:\n${errors.join("\n")}`);
  return parsed.data;
}

export async function loadTheme(path?: string): Promise<DeckTheme> {
  if (!path) return defaultTheme;
  const raw = JSON.parse(await readFile(path, "utf8")) as unknown;
  const parsed = themeInputSchema.safeParse(raw);
  if (!parsed.success) throw new Error(`Invalid theme file "${path}":\n${parsed.error.message}`);
  const logoPath = parsed.data.logo?.path ?? parsed.data.logoPath;
  const resolvedLogoPath = logoPath && !logoPath.startsWith("data:") && !isAbsolute(logoPath) ? resolve(path, "..", logoPath) : logoPath;
  return resolveTheme({ ...parsed.data, ...(resolvedLogoPath ? { logoPath: resolvedLogoPath, logo: parsed.data.logo ? { ...parsed.data.logo, path: resolvedLogoPath } : undefined } : {}) });
}

export function validateTheme(theme: unknown): string[] {
  const parsed = DeckThemeSchema.safeParse(theme);
  if (!parsed.success) return parsed.error.issues.map((issue) => `${issue.path.join(".") || "theme"}: ${issue.message}`);
  const errors: string[] = [];
  const logoPath = parsed.data.logo?.path ?? parsed.data.logoPath;
  if (logoPath && !logoPath.startsWith("data:") && !existsSync(logoPath)) errors.push(`logoPath does not exist: ${logoPath}`);
  return errors;
}
