import { readFile } from "node:fs/promises";

export type DeckTheme = {
  fontFace: string; headingFontFace: string; colors: { ink: string; muted: string; line: string; accent: string; canvas: string; surface: string };
  footer?: string; logoPath?: string; margin?: number;
};
export const defaultTheme: DeckTheme = { fontFace: "Aptos", headingFontFace: "Aptos Display", colors: { ink: "111827", muted: "6B7280", line: "E5E7EB", accent: "2563EB", canvas: "FFFFFF", surface: "F9FAFB" }, footer: "Generated by Local Deck AI", margin: 0.85 };
export async function loadTheme(path?: string): Promise<DeckTheme> {
  if (!path) return defaultTheme;
  const parsed = JSON.parse(await readFile(path, "utf8")) as Partial<DeckTheme>;
  return { ...defaultTheme, ...parsed, colors: { ...defaultTheme.colors, ...(parsed.colors ?? {}) } };
}
export function validateTheme(theme: DeckTheme): string[] {
  const errors: string[] = [];
  if (!theme.fontFace.trim() || !theme.headingFontFace.trim()) errors.push("fontFace and headingFontFace are required");
  for (const [key, value] of Object.entries(theme.colors)) if (!/^[0-9a-f]{6}$/i.test(value)) errors.push(`colors.${key} must be a 6-digit hex color`);
  return errors;
}
