import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import PptxGenJS from "pptxgenjs";
import type { Presentation, Slide } from "../schemas/presentation.js";
import { defaultTheme, resolveTheme, type DeckTheme } from "../theme/theme.js";
import { validateTemplateForPresentation, type TemplateDefinition } from "../template/template.js";

type PptxSlide = {
  background: { color: string };
  addText: (...args: unknown[]) => void;
  addShape: (...args: unknown[]) => void;
  addImage?: (...args: unknown[]) => void;
  addNotes?: (notes: string) => void;
};
type PptxDeck = {
  layout: string;
  author: string;
  subject: string;
  title: string;
  company: string;
  lang: string;
  addSlide: () => PptxSlide;
  writeFile: (options: { fileName: string }) => Promise<unknown>;
};

const shapeType = { line: "line", roundRect: "roundRect" } as const;

export async function renderPresentationToPptx(
  presentation: Presentation,
  outputPath: string,
  onProgress?: (message: string, percent: number) => void,
  customTheme: DeckTheme = defaultTheme,
  template?: TemplateDefinition
): Promise<void> {
  const theme = resolveTheme(customTheme);
  if (template) {
    const templateErrors = validateTemplateForPresentation(template, presentation);
    if (templateErrors.length > 0) throw new Error(`Template cannot render this presentation:\n${templateErrors.join("\n")}`);
  }
  const PptxGenJSConstructor = PptxGenJS as unknown as new () => PptxDeck;
  const deck = new PptxGenJSConstructor();
  deck.layout = "LAYOUT_WIDE";
  deck.author = "Local Deck AI";
  deck.subject = presentation.sourceSummary ?? "Generated by Local Deck AI";
  deck.title = presentation.title;
  deck.company = "Local Deck AI";
  deck.lang = "ja-JP";

  for (const [index, slideModel] of presentation.slides.entries()) {
    renderSlide(deck, slideModel, presentation, theme);
    onProgress?.(`スライドを描画しています (${index + 1}/${presentation.slides.length})`, 82 + Math.round(((index + 1) / presentation.slides.length) * 15));
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await deck.writeFile({ fileName: outputPath });
  onProgress?.("PowerPointファイルを書き出しました", 100);
}

function renderSlide(deck: PptxDeck, slideModel: Slide, presentation: Presentation, theme: DeckTheme): void {
  const slide = deck.addSlide();
  slide.background = { color: theme.colors.canvas };
  addFooter(slide, presentation, theme);
  switch (slideModel.layout) {
    case "title": renderTitleSlide(slide, slideModel, theme); break;
    case "agenda": renderAgendaSlide(slide, slideModel, theme); break;
    case "comparison": renderComparisonSlide(slide, slideModel, theme); break;
    case "process": renderProcessSlide(slide, slideModel, theme); break;
    case "summary": renderSummarySlide(slide, slideModel, theme); break;
    case "table": renderTableSlide(slide, slideModel, theme); break;
    case "timeline": renderTimelineSlide(slide, slideModel, theme); break;
    case "key-message": renderKeyMessageSlide(slide, slideModel, theme); break;
    case "content": default: renderContentSlide(slide, slideModel, theme); break;
  }
  if (slideModel.speakerNotes || slideModel.citations?.length) {
    const sources = slideModel.citations?.length ? `\n\nSources:\n${slideModel.citations.map((citation) => `- ${citation.source}${citation.page ? ` (p.${citation.page})` : ""}`).join("\n")}` : "";
    slide.addNotes?.(`${slideModel.speakerNotes ?? ""}${sources}`.trim());
  }
}

function renderTitleSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  slide.addText(model.title, { x: theme.margin, y: 2.25, w: 11.7, h: 0.8, fontFace: theme.headingFontFace, fontSize: 40, bold: true, color: theme.colors.ink, margin: 0, fit: "shrink" });
  if (model.subtitle) slide.addText(model.subtitle, { x: theme.margin, y: 3.2, w: 10.5, h: 0.5, fontFace: theme.fontFace, fontSize: 18, color: theme.colors.muted, margin: 0, fit: "shrink" });
}

function renderAgendaSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  const items = model.bullets.length > 0 ? model.bullets : model.steps ?? [];
  items.slice(0, 8).forEach((item, index) => {
    slide.addText(String(index + 1).padStart(2, "0"), { x: theme.margin + 0.15, y: 1.55 + index * 0.55, w: 0.6, h: 0.3, fontFace: theme.fontFace, fontSize: 12, bold: true, color: theme.colors.accent, margin: 0 });
    slide.addText(item, { x: theme.margin + 0.9, y: 1.48 + index * 0.55, w: 10.4, h: 0.4, fontFace: theme.fontFace, fontSize: 18, color: theme.colors.ink, margin: 0, fit: "shrink" });
  });
}

function renderContentSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  if (model.subtitle) slide.addText(model.subtitle, { x: theme.margin + 0.05, y: 1.18, w: 11.2, h: 0.4, fontFace: theme.fontFace, fontSize: 14, color: theme.colors.muted, margin: 0, fit: "shrink" });
  addBullets(slide, model.bullets, theme.margin + 0.1, model.subtitle ? 1.78 : 1.55, 11.2, theme);
}

function renderComparisonSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  const columns = model.columns?.slice(0, 2) ?? [];
  const safeColumns = columns.length > 0 ? columns : [{ heading: "Before", items: model.bullets.slice(0, 3) }, { heading: "After", items: model.bullets.slice(3, 6) }];
  safeColumns.slice(0, 2).forEach((column, index) => {
    const x = index === 0 ? theme.margin + 0.05 : 6.85;
    slide.addShape(shapeType.roundRect, { x, y: 1.45, w: 5.45, h: 4.75, line: { color: theme.colors.line, width: 1 }, fill: { color: theme.colors.surface } });
    slide.addText(column.heading, { x: x + 0.35, y: 1.75, w: 4.75, h: 0.4, fontFace: theme.headingFontFace, fontSize: 20, bold: true, color: theme.colors.ink, margin: 0, fit: "shrink" });
    addBullets(slide, column.items, x + 0.35, 2.35, 4.8, theme, 16);
  });
}

function renderProcessSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  const steps = model.steps?.length ? model.steps : model.bullets;
  steps.slice(0, 5).forEach((step, index) => {
    const x = theme.margin + 0.05 + index * 2.45;
    slide.addShape(shapeType.roundRect, { x, y: 2.35, w: 2, h: 1.45, line: { color: theme.colors.line, width: 1 }, fill: { color: theme.colors.surface } });
    slide.addText(String(index + 1), { x: x + 0.2, y: 2.55, w: 0.35, h: 0.25, fontFace: theme.fontFace, fontSize: 11, bold: true, color: theme.colors.accent, margin: 0 });
    slide.addText(step, { x: x + 0.25, y: 2.9, w: 1.5, h: 0.65, fontFace: theme.fontFace, fontSize: 13, color: theme.colors.ink, fit: "shrink", margin: 0 });
    if (index < Math.min(steps.length, 5) - 1) slide.addShape(shapeType.line, { x: x + 2.05, y: 3.07, w: 0.32, h: 0, line: { color: theme.colors.accent, width: 1.2, endArrowType: "triangle" } });
  });
}

function renderSummarySlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void { addSlideTitle(slide, model.title, theme); addBullets(slide, model.bullets, theme.margin + 0.15, 1.55, 10.8, theme, 22); }

function renderTableSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  const table = model.table;
  if (!table) return renderContentSlide(slide, model, theme);
  const cols = table.headers.length;
  const rowH = Math.min(0.55, 4.6 / Math.max(table.rows.length + 1, 1));
  const colW = 11.2 / cols;
  table.headers.forEach((header, column) => slide.addText(header, { x: theme.margin - 0.05 + column * colW, y: 1.45, w: colW - 0.04, h: rowH, bold: true, fontFace: theme.fontFace, color: theme.colors.canvas, fill: { color: theme.colors.accent }, margin: 0.08, fit: "shrink" }));
  table.rows.slice(0, 12).forEach((row, rowIndex) => row.slice(0, cols).forEach((cell, column) => slide.addText(cell, { x: theme.margin - 0.05 + column * colW, y: 1.45 + (rowIndex + 1) * rowH, w: colW - 0.04, h: rowH, fontFace: theme.fontFace, color: theme.colors.ink, fill: { color: rowIndex % 2 ? theme.colors.surface : theme.colors.canvas }, margin: 0.08, fit: "shrink" })));
}

function renderTimelineSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void {
  addSlideTitle(slide, model.title, theme);
  const items = model.timeline ?? [];
  slide.addShape(shapeType.line, { x: theme.margin + 0.15, y: 3.2, w: 10.8, h: 0, line: { color: theme.colors.accent, width: 2 } });
  items.forEach((item, index) => {
    const x = theme.margin + 0.15 + index * (10.8 / Math.max(items.length - 1, 1));
    slide.addShape(shapeType.roundRect, { x: x - 0.08, y: 3.05, w: 0.16, h: 0.3, line: { color: theme.colors.accent }, fill: { color: theme.colors.accent } });
    slide.addText(item.date, { x: x - 0.6, y: 2.25, w: 1.2, h: 0.3, fontFace: theme.fontFace, fontSize: 12, bold: true, color: theme.colors.accent, align: "center", margin: 0, fit: "shrink" });
    slide.addText(item.label, { x: x - 0.8, y: 3.55, w: 1.6, h: 0.5, fontFace: theme.fontFace, fontSize: 13, bold: true, color: theme.colors.ink, align: "center", fit: "shrink", margin: 0 });
    if (item.description) slide.addText(item.description, { x: x - 0.85, y: 4.15, w: 1.7, h: 0.8, fontFace: theme.fontFace, fontSize: 10, color: theme.colors.muted, align: "center", fit: "shrink", margin: 0 });
  });
}

function renderKeyMessageSlide(slide: PptxSlide, model: Slide, theme: DeckTheme): void { addSlideTitle(slide, model.title, theme); slide.addText(model.keyMessage ?? model.bullets[0] ?? "", { x: 1.2, y: 2.25, w: 10, h: 1.5, fontFace: theme.headingFontFace, fontSize: 32, bold: true, color: theme.colors.accent, align: "center", valign: "mid", fit: "shrink", margin: 0.1 }); }

function addSlideTitle(slide: PptxSlide, title: string, theme: DeckTheme): void {
  slide.addText(title, { x: theme.margin, y: 0.55, w: 11.5, h: 0.45, fontFace: theme.headingFontFace, fontSize: 26, bold: true, color: theme.colors.ink, margin: 0, fit: "shrink" });
  slide.addShape(shapeType.line, { x: theme.margin, y: 1.13, w: 11.6, h: 0, line: { color: theme.colors.line, width: 1 } });
}

function addBullets(slide: PptxSlide, bullets: string[], x: number, y: number, w: number, theme: DeckTheme, fontSize = 18): void {
  bullets.slice(0, 8).forEach((bullet, index) => {
    slide.addText("•", { x, y: y + index * 0.58, w: 0.2, h: 0.3, fontFace: theme.fontFace, fontSize, color: theme.colors.accent, margin: 0 });
    slide.addText(bullet, { x: x + 0.35, y: y + index * 0.58, w: w - 0.35, h: 0.38, fontFace: theme.fontFace, fontSize, color: theme.colors.ink, fit: "shrink", margin: 0 });
  });
}

function addFooter(slide: PptxSlide, presentation: Presentation, theme: DeckTheme): void {
  slide.addText(theme.footer ?? presentation.title, { x: theme.margin, y: 6.95, w: 8.5, h: 0.2, fontFace: theme.fontFace, fontSize: 8, color: theme.colors.muted, margin: 0, fit: "shrink" });
  const logo = theme.logo ?? (theme.logoPath ? { path: theme.logoPath, x: 11.5, y: 6.75, w: 1, h: 0.35 } : undefined);
  if (logo && slide.addImage) slide.addImage({ path: logo.path, x: logo.x, y: logo.y, w: logo.w, h: logo.h });
}
