import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import PptxGenJS from "pptxgenjs";
import type { Presentation, Slide } from "../schemas/presentation.js";
import { defaultTheme, type DeckTheme } from "../theme/theme.js";

type PptxSlide = {
  background: { color: string };
  addText: (...args: unknown[]) => void;
  addShape: (...args: unknown[]) => void;
  addNotes?: (notes: string) => void;
};
type PptxDeck = {
  layout: string;
  author: string;
  subject: string;
  title: string;
  company: string;
  lang: string;
  addSlide: () => PptxSlide;
  writeFile: (options: { fileName: string }) => Promise<unknown>;
};

const shapeType = {
  line: "line",
  roundRect: "roundRect"
} as const;

const theme = {
  ink: "111827",
  muted: "6B7280",
  line: "E5E7EB",
  accent: "2563EB",
  canvas: "FFFFFF",
  surface: "F9FAFB"
};

export async function renderPresentationToPptx(
  presentation: Presentation,
  outputPath: string,
  onProgress?: (message: string, percent: number) => void,
  customTheme: DeckTheme = defaultTheme
): Promise<void> {
  const PptxGenJSConstructor = PptxGenJS as unknown as new () => PptxDeck;
  const deck = new PptxGenJSConstructor();
  deck.layout = "LAYOUT_WIDE";
  deck.author = "Local Deck AI";
  deck.subject = presentation.sourceSummary ?? "Generated by Local Deck AI";
  deck.title = presentation.title;
  deck.company = "Local Deck AI";
  deck.lang = "ja-JP";

  for (const [index, slideModel] of presentation.slides.entries()) {
    renderSlide(deck, slideModel, presentation, customTheme);
    onProgress?.(`スライドを描画しています (${index + 1}/${presentation.slides.length})`, 82 + Math.round(((index + 1) / presentation.slides.length) * 15));
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await deck.writeFile({ fileName: outputPath });
  onProgress?.("PowerPointファイルを書き出しました", 100);
}

function renderSlide(
  deck: PptxDeck,
  slideModel: Slide,
  presentation: Presentation,
  customTheme: DeckTheme
): void {
  const slide = deck.addSlide();
  slide.background = { color: theme.canvas };
  addFooter(slide, presentation);

  switch (slideModel.layout) {
    case "title":
      renderTitleSlide(slide, slideModel);
      break;
    case "agenda":
      renderAgendaSlide(slide, slideModel);
      break;
    case "comparison":
      renderComparisonSlide(slide, slideModel);
      break;
    case "process":
      renderProcessSlide(slide, slideModel);
      break;
    case "summary":
      renderSummarySlide(slide, slideModel);
      break;
    case "table": renderTableSlide(slide, slideModel); break;
    case "timeline": renderTimelineSlide(slide, slideModel); break;
    case "key-message": renderKeyMessageSlide(slide, slideModel); break;
    case "content":
    default:
      renderContentSlide(slide, slideModel);
      break;
  }

  if (slideModel.speakerNotes) {
    slide.addNotes?.(`${slideModel.speakerNotes}${slideModel.citations?.length ? `\n\nSources:\n${slideModel.citations.map((c) => `- ${c.source}${c.page ? ` (p.${c.page})` : ""}`).join("\n")}` : ""}`);
  }
}

function renderTableSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title); const table = slideModel.table;
  if (!table) return renderContentSlide(slide, slideModel);
  const cols = table.headers.length; const rowH = Math.min(0.55, 4.6 / Math.max(table.rows.length + 1, 1)); const colW = 11.2 / cols;
  table.headers.forEach((header, c) => slide.addText(header, { x: 0.8 + c * colW, y: 1.45, w: colW - 0.04, h: rowH, bold: true, color: theme.canvas, fill: { color: theme.accent }, margin: 0.08, fit: "shrink" }));
  table.rows.slice(0, 12).forEach((row, r) => row.slice(0, cols).forEach((cell, c) => slide.addText(cell, { x: 0.8 + c * colW, y: 1.45 + (r + 1) * rowH, w: colW - 0.04, h: rowH, color: theme.ink, fill: { color: r % 2 ? theme.surface : theme.canvas }, margin: 0.08, fit: "shrink" })));
}
function renderTimelineSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title); const items = slideModel.timeline ?? [];
  slide.addShape(shapeType.line, { x: 1, y: 3.2, w: 10.8, h: 0, line: { color: theme.accent, width: 2 } });
  items.forEach((item, i) => { const x = 1 + i * (10.8 / Math.max(items.length - 1, 1)); slide.addShape(shapeType.roundRect, { x: x - 0.08, y: 3.05, w: 0.16, h: 0.3, line: { color: theme.accent }, fill: { color: theme.accent } }); slide.addText(item.date, { x: x - 0.6, y: 2.25, w: 1.2, h: 0.3, fontSize: 12, bold: true, color: theme.accent, align: "center", margin: 0 }); slide.addText(item.label, { x: x - 0.8, y: 3.55, w: 1.6, h: 0.5, fontSize: 13, bold: true, color: theme.ink, align: "center", fit: "shrink", margin: 0 }); });
}
function renderKeyMessageSlide(slide: PptxSlide, slideModel: Slide): void { addSlideTitle(slide, slideModel.title); slide.addText(slideModel.keyMessage ?? slideModel.bullets[0] ?? "", { x: 1.2, y: 2.25, w: 10, h: 1.5, fontFace: "Aptos Display", fontSize: 32, bold: true, color: theme.accent, align: "center", valign: "mid", fit: "shrink", margin: 0.1 }); }

function renderTitleSlide(slide: PptxSlide, slideModel: Slide): void {
  slide.addText(slideModel.title, {
    x: 0.8,
    y: 2.25,
    w: 11.7,
    h: 0.8,
    fontFace: "Aptos Display",
    fontSize: 40,
    bold: true,
    color: theme.ink,
    margin: 0
  });

  if (slideModel.subtitle) {
    slide.addText(slideModel.subtitle, {
      x: 0.85,
      y: 3.2,
      w: 10.5,
      h: 0.5,
      fontFace: "Aptos",
      fontSize: 18,
      color: theme.muted,
      margin: 0
    });
  }
}

function renderAgendaSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const items = slideModel.bullets.length > 0 ? slideModel.bullets : slideModel.steps ?? [];

  items.slice(0, 8).forEach((item, index) => {
    slide.addText(String(index + 1).padStart(2, "0"), {
      x: 1.0,
      y: 1.55 + index * 0.55,
      w: 0.6,
      h: 0.3,
      fontFace: "Aptos",
      fontSize: 12,
      bold: true,
      color: theme.accent,
      margin: 0
    });
    slide.addText(item, {
      x: 1.75,
      y: 1.48 + index * 0.55,
      w: 10.4,
      h: 0.4,
      fontFace: "Aptos",
      fontSize: 18,
      color: theme.ink,
      margin: 0
    });
  });
}

function renderContentSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);

  if (slideModel.subtitle) {
    slide.addText(slideModel.subtitle, {
      x: 0.9,
      y: 1.18,
      w: 11.2,
      h: 0.4,
      fontFace: "Aptos",
      fontSize: 14,
      color: theme.muted,
      margin: 0
    });
  }

  addBullets(slide, slideModel.bullets, 0.95, slideModel.subtitle ? 1.78 : 1.55, 11.2);
}

function renderComparisonSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const columns = slideModel.columns?.slice(0, 2) ?? [];
  const safeColumns = columns.length > 0 ? columns : [
    { heading: "Before", items: slideModel.bullets.slice(0, 3) },
    { heading: "After", items: slideModel.bullets.slice(3, 6) }
  ];

  safeColumns.slice(0, 2).forEach((column, index) => {
    const x = index === 0 ? 0.9 : 6.85;
    slide.addShape(shapeType.roundRect, {
      x,
      y: 1.45,
      w: 5.45,
      h: 4.75,
      line: { color: theme.line, width: 1 },
      fill: { color: theme.surface }
    });
    slide.addText(column.heading, {
      x: x + 0.35,
      y: 1.75,
      w: 4.75,
      h: 0.4,
      fontFace: "Aptos Display",
      fontSize: 20,
      bold: true,
      color: theme.ink,
      margin: 0
    });
    addBullets(slide, column.items, x + 0.35, 2.35, 4.8);
  });
}

function renderProcessSlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const steps = slideModel.steps?.length ? slideModel.steps : slideModel.bullets;

  steps.slice(0, 5).forEach((step, index) => {
    const x = 0.9 + index * 2.45;
    slide.addShape(shapeType.roundRect, {
      x,
      y: 2.35,
      w: 2.0,
      h: 1.45,
      line: { color: theme.line, width: 1 },
      fill: { color: theme.surface }
    });
    slide.addText(String(index + 1), {
      x: x + 0.2,
      y: 2.55,
      w: 0.35,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 11,
      bold: true,
      color: theme.accent,
      margin: 0
    });
    slide.addText(step, {
      x: x + 0.25,
      y: 2.9,
      w: 1.5,
      h: 0.65,
      fontFace: "Aptos",
      fontSize: 13,
      color: theme.ink,
      fit: "shrink",
      margin: 0
    });

    if (index < Math.min(steps.length, 5) - 1) {
      slide.addShape(shapeType.line, {
        x: x + 2.05,
        y: 3.07,
        w: 0.32,
        h: 0,
        line: {
          color: theme.accent,
          width: 1.2,
          beginArrowType: "none",
          endArrowType: "triangle"
        }
      });
    }
  });
}

function renderSummarySlide(slide: PptxSlide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  addBullets(slide, slideModel.bullets, 1.0, 1.55, 10.8, 22);
}

function addSlideTitle(slide: PptxSlide, title: string): void {
  slide.addText(title, {
    x: 0.85,
    y: 0.55,
    w: 11.5,
    h: 0.45,
    fontFace: "Aptos Display",
    fontSize: 26,
    bold: true,
    color: theme.ink,
    margin: 0
  });
  slide.addShape(shapeType.line, {
    x: 0.85,
    y: 1.13,
    w: 11.6,
    h: 0,
    line: { color: theme.line, width: 1 }
  });
}

function addBullets(
  slide: PptxSlide,
  bullets: string[],
  x: number,
  y: number,
  w: number,
  fontSize = 18
): void {
  bullets.slice(0, 8).forEach((bullet, index) => {
    slide.addText("•", {
      x,
      y: y + index * 0.58,
      w: 0.2,
      h: 0.3,
      fontFace: "Aptos",
      fontSize,
      color: theme.accent,
      margin: 0
    });
    slide.addText(bullet, {
      x: x + 0.35,
      y: y + index * 0.58,
      w: w - 0.35,
      h: 0.38,
      fontFace: "Aptos",
      fontSize,
      color: theme.ink,
      fit: "shrink",
      margin: 0
    });
  });
}

function addFooter(slide: PptxSlide, presentation: Presentation): void {
  slide.addText(presentation.title, {
    x: 0.85,
    y: 6.95,
    w: 8.5,
    h: 0.2,
    fontFace: "Aptos",
    fontSize: 8,
    color: theme.muted,
    margin: 0
  });
}
