import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import pptxgen from "pptxgenjs";
import type { Presentation, Slide } from "../schemas/presentation.js";

const theme = {
  ink: "111827",
  muted: "6B7280",
  line: "E5E7EB",
  accent: "2563EB",
  canvas: "FFFFFF"
};

export async function renderPresentationToPptx(
  presentation: Presentation,
  outputPath: string
): Promise<void> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Local Deck AI";
  pptx.subject = presentation.sourceSummary ?? "Generated by Local Deck AI";
  pptx.title = presentation.title;
  pptx.company = "Local Deck AI";
  pptx.lang = "ja-JP";

  for (const slideModel of presentation.slides) {
    renderSlide(pptx, slideModel, presentation);
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await pptx.writeFile({ fileName: outputPath });
}

function renderSlide(
  pptx: pptxgen,
  slideModel: Slide,
  presentation: Presentation
): void {
  const slide = pptx.addSlide();
  slide.background = { color: theme.canvas };
  addFooter(slide, presentation);

  switch (slideModel.layout) {
    case "title":
      renderTitleSlide(slide, slideModel);
      break;
    case "agenda":
      renderAgendaSlide(slide, slideModel);
      break;
    case "comparison":
      renderComparisonSlide(slide, slideModel);
      break;
    case "process":
      renderProcessSlide(slide, slideModel);
      break;
    case "summary":
      renderSummarySlide(slide, slideModel);
      break;
    case "content":
    default:
      renderContentSlide(slide, slideModel);
      break;
  }

  if (slideModel.speakerNotes) {
    const slideWithNotes = slide as unknown as { addNotes?: (notes: string) => void };
    slideWithNotes.addNotes?.(slideModel.speakerNotes);
  }
}

function renderTitleSlide(slide: pptxgen.Slide, slideModel: Slide): void {
  slide.addText(slideModel.title, {
    x: 0.8,
    y: 2.25,
    w: 11.7,
    h: 0.8,
    fontFace: "Aptos Display",
    fontSize: 40,
    bold: true,
    color: theme.ink,
    margin: 0
  });

  if (slideModel.subtitle) {
    slide.addText(slideModel.subtitle, {
      x: 0.85,
      y: 3.2,
      w: 10.5,
      h: 0.5,
      fontFace: "Aptos",
      fontSize: 18,
      color: theme.muted,
      margin: 0
    });
  }
}

function renderAgendaSlide(slide: pptxgen.Slide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const items = slideModel.bullets.length > 0 ? slideModel.bullets : slideModel.steps ?? [];
  items.slice(0, 8).forEach((item, index) => {
    slide.addText(String(index + 1).padStart(2, "0"), {
      x: 1.0,
      y: 1.55 + index * 0.55,
      w: 0.6,
      h: 0.3,
      fontFace: "Aptos",
      fontSize: 12,
      bold: true,
      color: theme.accent,
      margin: 0
    });
    slide.addText(item, {
      x: 1.75,
      y: 1.48 + index * 0.55,
      w: 10.4,
      h: 0.4,
      fontFace: "Aptos",
      fontSize: 18,
      color: theme.ink,
      margin: 0
    });
  });
}

function renderContentSlide(slide: pptxgen.Slide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  if (slideModel.subtitle) {
    slide.addText(slideModel.subtitle, {
      x: 0.9,
      y: 1.18,
      w: 11.2,
      h: 0.4,
      fontFace: "Aptos",
      fontSize: 14,
      color: theme.muted,
      margin: 0
    });
  }
  addBullets(slide, slideModel.bullets, 0.95, slideModel.subtitle ? 1.78 : 1.55, 11.2);
}

function renderComparisonSlide(slide: pptxgen.Slide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const columns = slideModel.columns?.slice(0, 2) ?? [];
  const safeColumns = columns.length > 0 ? columns : [
    { heading: "Before", items: slideModel.bullets.slice(0, 3) },
    { heading: "After", items: slideModel.bullets.slice(3, 6) }
  ];

  safeColumns.slice(0, 2).forEach((column, index) => {
    const x = index === 0 ? 0.9 : 6.85;
    slide.addShape(pptx.ShapeType.roundRect, {
      x,
      y: 1.45,
      w: 5.45,
      h: 4.75,
      rectRadius: 0.08,
      line: { color: theme.line, width: 1 },
      fill: { color: "F9FAFB" }
    });
    slide.addText(column.heading, {
      x: x + 0.35,
      y: 1.75,
      w: 4.75,
      h: 0.4,
      fontFace: "Aptos Display",
      fontSize: 20,
      bold: true,
      color: theme.ink,
      margin: 0
    });
    addBullets(slide, column.items, x + 0.35, 2.35, 4.8);
  });
}

function renderProcessSlide(slide: pptxgen.Slide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  const steps = slideModel.steps?.length ? slideModel.steps : slideModel.bullets;
  steps.slice(0, 5).forEach((step, index) => {
    const x = 0.9 + index * 2.45;
    slide.addShape(pptx.ShapeType.roundRect, {
      x,
      y: 2.35,
      w: 2.0,
      h: 1.45,
      rectRadius: 0.08,
      line: { color: theme.line, width: 1 },
      fill: { color: "F9FAFB" }
    });
    slide.addText(String(index + 1), {
      x: x + 0.2,
      y: 2.55,
      w: 0.35,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 11,
      bold: true,
      color: theme.accent,
      margin: 0
    });
    slide.addText(step, {
      x: x + 0.25,
      y: 2.9,
      w: 1.5,
      h: 0.65,
      fontFace: "Aptos",
      fontSize: 13,
      color: theme.ink,
      fit: "shrink",
      margin: 0
    });

    if (index < Math.min(steps.length, 5) - 1) {
      slide.addShape(pptx.ShapeType.line, {
        x: x + 2.05,
        y: 3.07,
        w: 0.32,
        h: 0,
        line: { color: theme.accent, width: 1.2, beginArrowType: "none", endArrowType: "triangle" }
      });
    }
  });
}

function renderSummarySlide(slide: pptxgen.Slide, slideModel: Slide): void {
  addSlideTitle(slide, slideModel.title);
  addBullets(slide, slideModel.bullets, 1.0, 1.55, 10.8, 22);
}

function addSlideTitle(slide: pptxgen.Slide, title: string): void {
  slide.addText(title, {
    x: 0.85,
    y: 0.55,
    w: 11.5,
    h: 0.45,
    fontFace: "Aptos Display",
    fontSize: 26,
    bold: true,
    color: theme.ink,
    margin: 0
  });
  slide.addShape(pptx.ShapeType.line, {
    x: 0.85,
    y: 1.13,
    w: 11.6,
    h: 0,
    line: { color: theme.line, width: 1 }
  });
}

function addBullets(
  slide: pptxgen.Slide,
  bullets: string[],
  x: number,
  y: number,
  w: number,
  fontSize = 18
): void {
  bullets.slice(0, 8).forEach((bullet, index) => {
    slide.addText("•", {
      x,
      y: y + index * 0.58,
      w: 0.2,
      h: 0.3,
      fontFace: "Aptos",
      fontSize,
      color: theme.accent,
      margin: 0
    });
    slide.addText(bullet, {
      x: x + 0.35,
      y: y + index * 0.58,
      w: w - 0.35,
      h: 0.38,
      fontFace: "Aptos",
      fontSize,
      color: theme.ink,
      fit: "shrink",
      margin: 0
    });
  });
}

function addFooter(slide: pptxgen.Slide, presentation: Presentation): void {
  slide.addText(presentation.title, {
    x: 0.85,
    y: 6.95,
    w: 8.5,
    h: 0.2,
    fontFace: "Aptos",
    fontSize: 8,
    color: theme.muted,
    margin: 0
  });
}
